version: '3.8'

services:
  bot:
    build: .
    ports:
      - "3001:3000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
